name: Build workflow

run-name: executed by ${{ github.actor }} 

on:
  workflow_dispatch:    
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: graph-nestjs-app
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  # run:
  #   runs-on: ubuntu-latest

  #   steps:
  #     run: docker run --rm -p 4000:4000 graphql-nestjs-app 
